# Generated by Django 5.2.15 on 2026-09-12 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0026_alter_characterownership_user_and_more'),
        ('srp', '0007_alter_srpuserrequest_options'),
        ('srp_access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposedsrpfleet',
            name='fleet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='srp_access_exposure', to='srp.srpfleetmain', verbose_name='built-in SRP fleet'),
        ),
        migrations.AlterField(
            model_name='srpaccesssettings',
            name='allow_any_public_state',
            field=models.BooleanField(default=True, help_text='When enabled, users must belong to a State whose public flag is set. When disabled, users must belong to one of the selected States.', verbose_name='allow any public state'),
        ),
        migrations.AlterField(
            model_name='srpaccesssettings',
            name='required_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.group', verbose_name='required access group'),
        ),
        migrations.AlterField(
            model_name='srpaccesssettings',
            name='selected_states',
            field=models.ManyToManyField(blank=True, related_name='+', to='authentication.state', verbose_name='selected states'),
        ),
    ]
